### ISSUE TITLE
[Bug] npm i -g dl-iconfont does not install the CLI. Can't use the package?

### ISSUE THREAD

**Issue by futuremotiondev** [un-ts/dl-iconfont#63]
I ran `npm i -g dl-iconfont`. No CLI is installed. 

`dli: The term 'dli' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

`dl-iconfont: The term 'dl-iconfont' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

Node: v21.6.2

**Comment by JounQin** [comment]
fixed in v0.4.2
